# =============================================================================
# Node Exporter Handlers - Node Exporter 处理器 | Node Exporter Handlers
# =============================================================================
# 定义 Node Exporter 服务的处理器
# Define handlers for Node Exporter service
# =============================================================================

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
