---
# Promtail role - Loki 日志收集代理
# 安装和配置 Grafana Loki Promtail

- name: Check if promtail is already installed
  stat:
    path: /usr/local/bin/promtail
  register: promtail_binary

- name: Get installed promtail version
  shell: /usr/local/bin/promtail --version 2>&1 | grep -oP 'version \K[0-9.]+'
  register: installed_version
  when: promtail_binary.stat.exists
  changed_when: false
  failed_when: false

- name: Detect system architecture
  set_fact:
    promtail_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Download and install promtail
  block:
    - name: Create temporary directory
      file:
        path: /tmp/promtail
        state: directory
        mode: '0755'

    - name: Download promtail
      get_url:
        url: "{{ loki.promtail.download_url }}/v{{ loki.promtail.version }}/promtail-linux-{{ promtail_arch }}.zip"
        dest: "/tmp/promtail/promtail-linux-{{ promtail_arch }}.zip"
        mode: '0644'

    - name: Extract promtail
      unarchive:
        src: "/tmp/promtail/promtail-linux-{{ promtail_arch }}.zip"
        dest: /tmp/promtail
        remote_src: yes

    - name: Copy promtail binary
      copy:
        src: "/tmp/promtail/promtail-linux-{{ promtail_arch }}"
        dest: /usr/local/bin/promtail
        mode: '0755'
        remote_src: yes

    - name: Clean up temporary files
      file:
        path: /tmp/promtail
        state: absent
  when: >
    not promtail_binary.stat.exists or
    (installed_version.stdout is defined and installed_version.stdout != loki.promtail.version)

- name: Create promtail user
  user:
    name: promtail
    system: yes
    shell: /bin/false
    create_home: no
    groups: adm  # Add to adm group to read log files

- name: Create promtail config directory
  file:
    path: /etc/promtail
    state: directory
    mode: '0755'
    owner: promtail
    group: promtail

- name: Create promtail positions directory
  file:
    path: /var/lib/promtail
    state: directory
    mode: '0755'
    owner: promtail
    group: promtail

- name: Deploy promtail configuration
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail/config.yml
    mode: '0644'
    owner: promtail
    group: promtail
  notify: restart promtail

- name: Create promtail systemd service
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: '0644'
  notify:
    - reload systemd
    - restart promtail

- name: Enable and start promtail
  service:
    name: promtail
    state: started
    enabled: yes

- name: Verify promtail is responding
  uri:
    url: "http://localhost:{{ loki.promtail.port }}/ready"
    status_code: 200
  register: promtail_health
  retries: 3
  delay: 5
  until: promtail_health.status == 200
  ignore_errors: yes
