all:
  children:
    # -- 跳板机/堡垒机组 --
    jump_servers:
      hosts:
        jumphost-01:
          ansible_host: 192.168.1.10 # 跳板机的公网IP

    # -- 按地理位置分组 --
    ---
# Ansible Inventory for AnixOps
# 所有主机信息和变量都将从 GitHub Secrets 中读取
# 在 GitHub Actions 中设置以下 Secrets:
# - SERVER_IPS: 服务器 IP 列表 (JSON 格式)
# - SSH_PRIVATE_KEY: SSH 私钥
# - ANSIBLE_VAULT_PASSWORD: Vault 密码 (如需要)

all:
  children:
    # Web 服务器组
    web_servers:
      hosts:
        # 示例配置 - 实际主机信息从环境变量或 GitHub Secrets 读取
        # web-01:
        #   ansible_host: "{{ lookup('env', 'WEB_01_IP') | default('192.168.1.10') }}"
      vars:
        server_role: web
        
    # 应用服务器组
    app_servers:
      hosts:
        # app-01:
        #   ansible_host: "{{ lookup('env', 'APP_01_IP') | default('192.168.1.20') }}"
      vars:
        server_role: app
        
    # 数据库服务器组
    db_servers:
      hosts:
        # db-01:
        #   ansible_host: "{{ lookup('env', 'DB_01_IP') | default('192.168.1.30') }}"
      vars:
        server_role: database
        
    # 监控服务器组
    monitoring_servers:
      hosts:
        # monitoring-01:
        #   ansible_host: "{{ lookup('env', 'MONITORING_IP') | default('192.168.1.100') }}"
      vars:
        server_role: monitoring

  vars:
    # 全局变量 - 所有服务器共享
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('root') }}"
    ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') | default('22') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    
    # Python 解释器路径
    ansible_python_interpreter: /usr/bin/python3
    
    # SSH 连接参数
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' # 日本区域服务器
      children:
        jp_web_servers:
          hosts:
            tokyo-web-01:
              ansible_host: 10.0.1.11 # 服务器内网IP
              # 指定通过哪个跳板机连接
              ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@192.168.1.10"'

    us_servers: # 美国区域服务器
      children:
        us_db_servers:
          hosts:
            california-db-01:
              ansible_host: 10.0.2.21 # 服务器内网IP
              ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@192.168.1.10"'

  # -- 全局变量 --
  vars:
    # 定义连接跳板机和目标服务器的默认用户
    ansible_user: ops-user
