---
# Ansible Inventory - Direct IP Connection
# Server IPs are read from environment variables
# For local use: copy .env.example to .env and configure
# For GitHub Actions: set as repository secrets

all:
  children:
    # Web 服务器组 - 部署 web 应用和服务
    web_servers:
      hosts:
        de-1:
          ansible_host: "{{ lookup('env', 'DE_1_V4_SSH') }}"
        jp-1:
          ansible_host: "{{ lookup('env', 'JP_1_V4_SSH') }}"
        uk-1:
          ansible_host: "{{ lookup('env', 'UK_1_V4_SSH') }}"
        us-w-1:
          ansible_host: "{{ lookup('env', 'US_W_1_V4_SSH') }}"
      vars:
        server_role: web
    
    # Proxy 服务器组 - PLG Stack
    proxy_servers:
      hosts:
        sg-1:
          ansible_host: "{{ lookup('env', 'SG_1_V4_SSH') }}"
        jp-2:
          ansible_host: "{{ lookup('env', 'JP_2_V4_SSH') }}"
        hk-1:
          ansible_host: "{{ lookup('env', 'HK_1_V4_SSH') }}"
        uk-2:
          ansible_host: "{{ lookup('env', 'UK_2_V4_SSH') }}"
      vars:
        server_role: proxy
    
    # 开发服务器组
    dev_servers:
      hosts:
        fr-1:
          ansible_host: "{{ lookup('env', 'FR_1_V4_SSH') }}"
      vars:
        server_role: development
    
    # 可观测性服务器组 (Prometheus + Loki + Grafana)
    observability:
      hosts:
        pl-1:
          ansible_host: "{{ lookup('env', 'PL_1_V4_SSH') }}"
      vars:
        server_role: observability

  # 全局变量
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('root') }}"
    ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') | default('22') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
    # Server aliases - copied from inventory/server_aliases.yml
    # 用于在 Prometheus/Grafana/Loki 中显示友好的服务器名称
    server_aliases:
      # Web 服务器
      de-1:
        alias: "德国-测试-1"
        description: "德国 Web 服务器 - 测试环境 - NubeCloud"
        location: "Germany"
        environment: "test"
        
      # Observability 服务器
      pl-1:
        alias: "波兰-1"
        description: "波兰 Observability 服务器 - PLG Stack - OVH"
        location: "Poland"
        environment: "production"

      sg-1:
        alias: "新加坡-1"
        description: "新加坡 Proxy 服务器 - PLG Stack - Aliyun"
        location: "Singapore"
        environment: "production"

      jp-1:
        alias: "日本-1"
        description: "日本 web 服务器 - 测试环境 - Oracle"
        location: "Japan"
        environment: "test"

      jp-2:
        alias: "日本-2"
        description: "日本 Proxy 服务器 - PLG Stack - Churros"
        location: "Japan"
        environment: "production"
        
      hk-1:
        alias: "香港-1"
        description: "香港 Proxy 服务器 - PLG Stack - Zouter"
        location: "Hong Kong"
        environment: "production"

      uk-1:
        alias: "英国-1"
        description: "英国 web 服务器 - 测试环境 - Oracle"
        location: "United Kingdom"
        environment: "test"

      uk-2:
        alias: "英国-2"
        description: "英国 Proxy 服务器 - PLG Stack - Akko"
        location: "United Kingdom"
        environment: "production"

      fr-1:
        alias: "法国-1"
        description: "法国 Development 服务器 - DEV - OVH"
        location: "France"
        environment: "development"

      us-w-1:
        alias: "美国西-1"
        description: "美国西 Web 服务器 - PLG Stack - Oracle"
        location: "United States"
        environment: "production"
