all:
  children:
    # -- 跳板机/堡垒机组 --
    jump_servers:
      hosts:
        jumphost-01:
          ansible_host: 192.168.1.10 # 跳板机的公网IP

    # -- 按地理位置分组 --
    jp_servers: # 日本区域服务器
      children:
        jp_web_servers:
          hosts:
            tokyo-web-01:
              ansible_host: 10.0.1.11 # 服务器内网IP
              # 指定通过哪个跳板机连接
              ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@192.168.1.10"'

    us_servers: # 美国区域服务器
      children:
        us_db_servers:
          hosts:
            california-db-01:
              ansible_host: 10.0.2.21 # 服务器内网IP
              ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@192.168.1.10"'

  # -- 全局变量 --
  vars:
    # 定义连接跳板机和目标服务器的默认用户
    ansible_user: ops-user
