---
# Ansible Inventory - Direct IP Connection
# Server IPs are read from environment variables
# For local use: copy .env.example to .env and configure
# For GitHub Actions: set as repository secrets

all:
  children:
    # Web 服务器组 - 部署 web 应用和服务
    web_servers:
      hosts:
        de-test-1:
          ansible_host: "{{ lookup('env', 'DE_1_V4_SSH') }}"
      vars:
        server_role: web
    
    # 可观测性服务器组 (Prometheus + Loki + Grafana)
    observability:
      hosts:
        pl-test-1:
          ansible_host: "{{ lookup('env', 'PL_1_V4_SSH') }}"
      vars:
        server_role: observability

  # 全局变量
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('root') }}"
    ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') | default('22') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
