# =============================================================================
# Common Role Handlers - 通用角色处理器 | Common Role Handlers
# =============================================================================
# 定义服务重启和重载的处理器
# Define handlers for service restart and reload operations
# =============================================================================

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart chrony
  service:
    name: "{{ 'chronyd' if ansible_os_family == 'RedHat' else 'chrony' }}"
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
