---
# Common role handlers

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
