---
# =============================================================================
# Prerequisites Checks
# =============================================================================

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Display Docker status
  ansible.builtin.debug:
    msg: "{{ 'Docker is installed: ' + docker_check.stdout if docker_check.rc == 0 else 'Docker is not installed' }}"

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is required but not installed. Please install Docker first."
  when: docker_check.rc != 0

- name: Check if kubectl is installed
  ansible.builtin.command: kubectl version --client
  register: kubectl_check
  failed_when: false
  changed_when: false

- name: Install kubectl if not present
  when: kubectl_check.rc != 0
  block:
    - name: Download kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: yes

    - name: Verify kubectl installation
      ansible.builtin.command: kubectl version --client
      changed_when: false

- name: Check if Helm is installed
  ansible.builtin.command: helm version
  register: helm_check
  failed_when: false
  changed_when: false

- name: Install Helm if not present
  when: helm_check.rc != 0
  block:
    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3.sh
        mode: '0755'

    - name: Install Helm
      ansible.builtin.command: /tmp/get-helm-3.sh
      become: yes
      changed_when: true

    - name: Verify Helm installation
      ansible.builtin.command: helm version
      changed_when: false

- name: Display tools status
  ansible.builtin.debug:
    msg:
      - "✅ Prerequisites check completed"
      - "Docker: Installed"
      - "kubectl: Installed"
      - "Helm: Installed"
