---
# =============================================================================
# Verify K8s Cluster
# =============================================================================

- name: Get cluster info
  ansible.builtin.command: kubectl cluster-info
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: cluster_info
  changed_when: false
  become: "{{ 'yes' if k8s_provider == 'k3s' else 'no' }}"

- name: Get cluster nodes
  ansible.builtin.command: kubectl get nodes
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: cluster_nodes
  changed_when: false
  become: "{{ 'yes' if k8s_provider == 'k3s' else 'no' }}"

- name: Display cluster information
  ansible.builtin.debug:
    msg:
      - "🎉 Kubernetes Cluster Verification"
      - "=================================="
      - "{{ cluster_info.stdout_lines }}"
      - ""
      - "Nodes:"
      - "{{ cluster_nodes.stdout_lines }}"

- name: Wait for all system pods to be ready
  ansible.builtin.command: |
    kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: pods_ready
  changed_when: false
  failed_when: false
  become: "{{ 'yes' if k8s_provider == 'k3s' else 'no' }}"

- name: Display system pods status
  ansible.builtin.command: kubectl get pods -n kube-system
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: system_pods
  changed_when: false
  become: "{{ 'yes' if k8s_provider == 'k3s' else 'no' }}"

- name: Show system pods
  ansible.builtin.debug:
    msg:
      - "System Pods Status:"
      - "{{ system_pods.stdout_lines }}"
