---
# =============================================================================
# anix_cloudflared Role Handlers | Handlers for anix_cloudflared Role
# =============================================================================

# -----------------------------------------------------------------------------
# Cloudflared 服务管理 | Cloudflared Service Management
# -----------------------------------------------------------------------------

- name: Restart cloudflared service
  ansible.builtin.systemd:
    name: "{{ anix_cloudflared_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Stop cloudflared service
  ansible.builtin.systemd:
    name: "{{ anix_cloudflared_service_name }}"
    state: stopped
  become: yes

- name: Start cloudflared service
  ansible.builtin.systemd:
    name: "{{ anix_cloudflared_service_name }}"
    state: started
    enabled: yes
  become: yes
