---
# WARP Connector 默认配置
# WARP Connector Default Configuration

# WARP Connector token (必须提供)
# WARP Connector token (required)
warp_token: ""

# 安装方式
warp_install_method: "package"  # package 或 docker

# 包管理配置
warp_package_name: "cloudflare-warp"
warp_service_name: "warp-svc"

# Docker 配置 (如果使用 docker 方式)
warp_docker_image: "cloudflare/cloudflare-warp-connector:latest"
warp_docker_container_name: "warp-connector"
warp_docker_restart_policy: "unless-stopped"

# 网络配置
warp_allow_interfaces: []  # 允许的网络接口，留空表示全部
warp_routes: []  # 需要通告的路由

# 日志配置
warp_log_level: "info"  # debug, info, warn, error

# 系统配置
warp_config_dir: "/etc/cloudflare-warp"
warp_data_dir: "/var/lib/cloudflare-warp"

# 健康检查
warp_health_check_enabled: true
warp_health_check_interval: 60  # 秒
