---
# Prometheus Server Installation Tasks

- name: Create prometheus system group
  group:
    name: prometheus
    state: present
    system: yes

- name: Create prometheus system user
  user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download and install Prometheus
  block:
    - name: Check if Prometheus is already installed
      stat:
        path: /usr/local/bin/prometheus
      register: prometheus_bin

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version | default('2.45.0') }}/prometheus-{{ prometheus.version | default('2.45.0') }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
        mode: '0644'
      when: not prometheus_bin.stat.exists

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp
        remote_src: yes
      when: not prometheus_bin.stat.exists

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus.version | default('2.45.0') }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: prometheus
        group: prometheus
        mode: '0755'
        remote_src: yes
      loop:
        - prometheus
        - promtool
      when: not prometheus_bin.stat.exists

    - name: Copy Prometheus console files
      copy:
        src: "/tmp/prometheus-{{ prometheus.version | default('2.45.0') }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        owner: prometheus
        group: prometheus
        remote_src: yes
      loop:
        - consoles
        - console_libraries
      when: not prometheus_bin.stat.exists

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify: restart prometheus

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Display Prometheus info
  debug:
    msg: |
      Prometheus installed successfully
      Access: http://{{ ansible_host }}:9090
      Config: /etc/prometheus/prometheus.yml
      Data: /var/lib/prometheus
