---
# Quick Setup Playbook
# 仅部署基础配置、监控和防火墙，用于快速初始化新服务器

- name: Quick server setup
  hosts: all
  become: yes
  gather_facts: yes
  
  roles:
    - common
    - node_exporter
    - promtail
    - monitoring_firewall

  post_tasks:
    - name: Display quick setup summary
      debug:
        msg: |
          ═══════════════════════════════════════════════════════════
          ✓ Quick setup completed for {{ inventory_hostname }}
          ═══════════════════════════════════════════════════════════
          Components installed:
          ✓ Common configuration applied
          ✓ Node Exporter installed (port {{ prometheus.node_exporter.port }})
          ✓ Promtail configured for log collection (port {{ loki.promtail.port }})
          ✓ Firewall rules configured:
            - Public ports: {{ firewall_public_ports | join(', ') }}
            - Restricted ports: {{ firewall_restricted_ports | join(', ') }}
            - Whitelisted IPs: {{ monitoring_whitelist | length }}
          ═══════════════════════════════════════════════════════════
