---
# AnixOps Main Playbook
# 这是主 playbook，用于完整部署所有服务器配置

- name: Deploy Common Configuration
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common

- name: Deploy Node Exporter (Monitoring)
  hosts: all
  become: yes
  roles:
    - node_exporter

- name: Deploy Promtail (Log Collection)
  hosts: all
  become: yes
  roles:
    - promtail

- name: Deploy Nginx (Web Servers)
  hosts: web_servers
  become: yes
  roles:
    - nginx

- name: Final Health Check
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Display deployment summary
      debug:
        msg: |
          ═══════════════════════════════════════════════════════════
          ✓ Deployment completed successfully for {{ inventory_hostname }}
          ═══════════════════════════════════════════════════════════
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address | default('N/A') }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          
          Services Deployed:
          ✓ Common configuration (security, timezone, users)
          ✓ Node Exporter (port {{ prometheus.node_exporter.port }})
          ✓ Promtail (log collection)
          {% if inventory_hostname in groups['web_servers'] %}
          ✓ Nginx (HTTP/HTTPS)
          {% endif %}
          
          Next Steps:
          1. Verify in Grafana: {{ grafana.url }}
          2. Check Prometheus metrics: {{ prometheus.server_url }}
          3. Review logs in Loki: {{ loki.server_url }}
          ═══════════════════════════════════════════════════════════
