name: Ansible Test

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Select action'
        required: true
        default: 'ping-only'
        type: choice
        options:
          - ping-only
          - health-check.yml
          - quick-setup.yml
      target_group:
        description: 'Target servers'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - web_servers
          - observability
          - dev
          - prod
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  ping-test:
    name: Ansible Test & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create inventory from secrets
        run: |
      - name: Create inventory from config
        run: |
          echo "Generating inventory from servers-config.yml..."
          python3 tools/generate_inventory.py github-actions > inventory/hosts.yml
          
          echo "✓ Inventory generated"

      - name: Display Workflow Parameters
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "Workflow Configuration"
          echo "════════════════════════════════════════════════════════════"
          echo "Action: ${{ github.event.inputs.playbook || 'ping-only (auto)' }}"
          echo "Target: ${{ github.event.inputs.target_group || 'all (auto)' }}"
          echo "Trigger: ${{ github.event_name }}"
          echo "════════════════════════════════════════════════════════════"

      - name: Ping All Hosts
        if: github.event.inputs.playbook == 'ping-only' || github.event.inputs.playbook == '' || github.event_name != 'workflow_dispatch'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "Testing connectivity to ALL hosts..."
          echo "════════════════════════════════════════════════════════════"
          ansible all -i inventory/hosts.yml -m ping -v

      - name: Ping Web Servers
        if: github.event.inputs.playbook == 'ping-only' || github.event.inputs.playbook == '' || github.event_name != 'workflow_dispatch'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "Testing connectivity to WEB SERVERS..."
          echo "════════════════════════════════════════════════════════════"
          ansible web_servers -i inventory/hosts.yml -m ping -v

      - name: Ping Observability Servers
        if: github.event.inputs.playbook == 'ping-only' || github.event.inputs.playbook == '' || github.event_name != 'workflow_dispatch'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "Testing connectivity to OBSERVABILITY SERVERS..."
          echo "════════════════════════════════════════════════════════════"
          ansible observability -i inventory/hosts.yml -m ping -v

      - name: Gather Facts Test
        if: github.event.inputs.playbook == 'ping-only' || github.event.inputs.playbook == '' || github.event_name != 'workflow_dispatch'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "Testing fact gathering (setup module)..."
          echo "════════════════════════════════════════════════════════════"
          ansible all -i inventory/hosts.yml -m setup -a "filter=ansible_distribution*" -v
        continue-on-error: true

      - name: Run Ansible Playbook
        if: github.event.inputs.playbook != 'ping-only' && github.event.inputs.playbook != '' && github.event_name == 'workflow_dispatch'
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          TARGET="${{ github.event.inputs.target_group }}"
          PLAYBOOK="${{ github.event.inputs.playbook }}"
          
          echo "════════════════════════════════════════════════════════════"
          echo "Running Ansible Playbook"
          echo "════════════════════════════════════════════════════════════"
          echo "Playbook: playbooks/${PLAYBOOK}"
          echo "Target: ${TARGET}"
          echo "════════════════════════════════════════════════════════════"
          
          # Build and execute command
          CMD="ansible-playbook playbooks/${PLAYBOOK} -i inventory/hosts.yml --limit ${TARGET} -v"
          
          echo "Executing: $CMD"
          eval $CMD

      - name: Test Summary
        if: always()
        run: |
          echo "════════════════════════════════════════════════════════════"
          echo "✓ Ansible Workflow Completed"
          echo "════════════════════════════════════════════════════════════"
          echo "Test Run: $(date)"
          echo "Workflow: ${{ github.workflow }}"
          echo "Playbook: ${{ github.event.inputs.playbook || 'ping-only (auto)' }}"
          echo "Target: ${{ github.event.inputs.target_group || 'all (auto)' }}"
          echo "════════════════════════════════════════════════════════════"

      - name: Notify on failure
        if: failure()
        run: |
          echo "✗ Ansible workflow failed!"
          echo "Playbook: ${{ github.event.inputs.playbook || 'ping test' }}"
          echo "Target: ${{ github.event.inputs.target_group || 'all' }}"
          echo "Check the logs above for details."
