name: Ansible Lint

on:
  pull_request:
    branches: [ main, staging, deploy ]
  push:
    branches: [ main, staging, deploy ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Ansible Code
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ansible ansible-lint yamllint

      - name: Run yamllint
        run: |
          yamllint -c .yamllint.yml .
        continue-on-error: true

      - name: Run ansible-lint
        run: |
          ansible-lint --force-color playbooks/*.yml roles/*/tasks/*.yml
        continue-on-error: true

      - name: Syntax check all playbooks
        run: |
          ansible-playbook --syntax-check playbooks/site.yml
          ansible-playbook --syntax-check playbooks/quick-setup.yml
          ansible-playbook --syntax-check playbooks/web-servers.yml
          ansible-playbook --syntax-check playbooks/health-check.yml
          ansible-playbook --syntax-check playbooks/firewall-setup.yml
          ansible-playbook --syntax-check playbooks/observability.yml

      - name: Lint Summary
        if: always()
        run: |
          echo "════════════════════════════════════════════"
          echo "✓ Ansible Code Lint Completed"
          echo "════════════════════════════════════════════"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
          echo "════════════════════════════════════════════"
